import type { NextPage } from 'next'
import { useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Lottie from 'lottie-web'
import cashirSplashAnimation from '../public/16245-cashir-splash-animation.json'

const Home: NextPage = () => {
  useEffect(() => {
    Lottie.loadAnimation({
      container: document.querySelector('#react-lottie')!, // the dom element that will contain the animation
      animationData: cashirSplashAnimation, // the animation data
    });
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi bro how ho
        </h1>

        <div id="react-lottie" style={{ width: 600, height: 200 }}/>
        {/* <iframe src="https://embed.lottiefiles.com/animation/16245"></iframe> */}

        <h1 className={styles.title}>
          <a href="https://url.com/GpRzFf">tellings karo</a>
        </h1>
      </main>

      
    </div>
  )
}

export default Home
